Repository kubernetes-sigs/ibm-vpc-block-csi-driver, pull requests merged in 2021-08, with the labels that each got.

#22 To get coverage badge integrate with goveralls
  .travis.yml
Labels: cncf-cla: yes, lgtm, size/M, approved

#21 make paths aligned with kubernetes-sigs
  Dockerfile.builder
  MAINTAINERS.md
  Makefile
  OWNERS
  README.md
  cmd/main.go
  deploy/kubernetes/driver/kubernetes/delete-vpc-csi-driver.sh
  deploy/kubernetes/driver/kubernetes/deploy-vpc-block-driver.sh
  go.mod
  go.sum
  pkg/ibmcsidriver/constants.go
  scripts/build-bin.sh
  scripts/handleFailure.sh
  scripts/publishCoverage.sh
  tests/sanity/sanity_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#23 update coverage badge
  README.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#24 Edit build status badge
  Makefile
  README.md
Labels: cncf-cla: yes, lgtm, approved, size/S

#26 To add github actions for coverage
  .github/workflows/coverage.yml
Labels: cncf-cla: yes, lgtm, approved, size/S

#28 Fix github action issue
  .github/workflows/coverage.yml
Labels: cncf-cla: yes, lgtm, approved, size/S
